[project]
name = "ai-customer-ticket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.5",
    "sqlalchemy>=2.0.46",
]
